[build]
  command = "pip install -r requirements.txt"
  publish = ".netlify/dummy" # Points to an empty non-existent or dummy folder to force function routing

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Route EVERYTHING to the function to let Flask handle templates AND static files
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
